name: florayion
description: A data collection app for Project GTF.

version: 2.3.0+13

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  gradient_widgets: ^0.5.1
  firebase_analytics: ^5.0.11
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  flutter_spinkit: "^4.1.2"
  flutter_launcher_icons: ^0.7.4
  geolocator: ^5.3.1
  get_version: ^0.2.2
  path_provider: ^1.6.7
  path: ^1.7.0
  data_connection_checker: ^0.3.4
  encrypt: ^4.0.1
  moor_flutter: ^3.1.0
  shared_preferences: ^0.5.7+3
  google_maps_flutter: ^0.5.29
  provider: ^4.3.2
  flare_flutter: ^2.0.6


dev_dependencies:
  build_runner: ^1.10.0
  moor_generator: ^3.3.1
    
flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path : lib/ImageAsset/launcher_icon.png

flutter:

  uses-material-design: true

  assets:
    - lib/ImageAsset/splashScreen.png
    - lib/ImageAsset/background_1.jpg
    - lib/ImageAsset/background_2.jpg
    - lib/Animations/BackGroundForked.flr

  fonts:
    - family: CustIcons
      fonts:
        - asset: lib/IconAsset/CustIcons.ttf
    - family:  IC1
      fonts:
        - asset: lib/IconAsset/IC1.ttf
    - family: Lato
      fonts:
        - asset: lib/IconAsset/Lato-Regular.ttf
        - asset: lib/IconAsset/Lato-Bold.ttf
          weight: 700

